
REPLICANT_PATH:=$(shell git rev-parse --show-toplevel)
SPMD_NAME := asic-09-power-high-freq
include $(REPLICANT_PATH)/environment.mk
SPMD_SRC_PATH = $(BSG_MANYCORE_DIR)/software/spmd
include $(EXAMPLES_PATH)/spmd/loader.mk
