typedef uint32_t vertex_t;
static vertex_t columns [] = {
    26, // neighbors(0)
    53, // neighbors(1)
    // neighbors(2)
    // neighbors(3)
    // neighbors(4)
    // neighbors(5)
    37, 12, 12, 1, // neighbors(6)
    50, 55, 50, 25, 26, 26, 46, 17, 50, 18, 6, 50, 17, 57, // neighbors(7)
    // neighbors(8)
    // neighbors(9)
    8, // neighbors(10)
    37, 37, // neighbors(11)
    37, // neighbors(12)
    63, 18, // neighbors(13)
    // neighbors(14)
    12, 43, 15, 25, 6, 37, 37, 57, 37, 41, 25, 26, 35, 54, 57, 4, 15, 32, 48, 57, 26, 57, 57, 17, 41, 15, 10, 15, 26, 0, 1, 7, 3, 41, 63, 50, 7, 54, 50, 15, 46, 37, 7, 17, 17, 26, 18, // neighbors(15)
    // neighbors(16)
    37, 12, 24, 26, 19, // neighbors(17)
    36, // neighbors(18)
    // neighbors(19)
    // neighbors(20)
    // neighbors(21)
    // neighbors(22)
    // neighbors(23)
    // neighbors(24)
    9, // neighbors(25)
    23, 32, 24, 39, 38, // neighbors(26)
    // neighbors(27)
    // neighbors(28)
    // neighbors(29)
    // neighbors(30)
    // neighbors(31)
    // neighbors(32)
    // neighbors(33)
    11, // neighbors(34)
    26, // neighbors(35)
    43, // neighbors(36)
    // neighbors(37)
    // neighbors(38)
    // neighbors(39)
    // neighbors(40)
    // neighbors(41)
    37, // neighbors(42)
    44, // neighbors(43)
    // neighbors(44)
    // neighbors(45)
    40, 23, // neighbors(46)
    // neighbors(47)
    // neighbors(48)
    // neighbors(49)
    17, 43, 12, 0, 52, 26, 43, 48, 12, 50, 12, 37, 48, 63, 13, 57, // neighbors(50)
    // neighbors(51)
    // neighbors(52)
    // neighbors(53)
    26, 1, // neighbors(54)
    25, 54, // neighbors(55)
    // neighbors(56)
    26, 37, 54, 3, 43, 37, 54, 46, 38, 41, 17, 26, 26, 6, 54, // neighbors(57)
    41, // neighbors(58)
    // neighbors(59)
    // neighbors(60)
    // neighbors(61)
    // neighbors(62)
    // neighbors(63)
};

static vertex_t row_ptrs [] = {
    0, // 0
    1, // 1
    2, // 2
    2, // 3
    2, // 4
    2, // 5
    2, // 6
    6, // 7
    20, // 8
    20, // 9
    20, // 10
    21, // 11
    23, // 12
    24, // 13
    26, // 14
    26, // 15
    73, // 16
    73, // 17
    78, // 18
    79, // 19
    79, // 20
    79, // 21
    79, // 22
    79, // 23
    79, // 24
    79, // 25
    80, // 26
    85, // 27
    85, // 28
    85, // 29
    85, // 30
    85, // 31
    85, // 32
    85, // 33
    85, // 34
    86, // 35
    87, // 36
    88, // 37
    88, // 38
    88, // 39
    88, // 40
    88, // 41
    88, // 42
    89, // 43
    90, // 44
    90, // 45
    90, // 46
    92, // 47
    92, // 48
    92, // 49
    92, // 50
    108, // 51
    108, // 52
    108, // 53
    108, // 54
    110, // 55
    112, // 56
    112, // 57
    127, // 58
    128, // 59
    128, // 60
    128, // 61
    128, // 62
    128, // 63
};
