REGRESSION_TESTS_TYPE = python

C_REGRESSION_TESTS = test_python

CXX_REGRESSION_TESTS =

REGRESSION_DEFINES = -DBSG_MANYCORE_DIR=$(BSG_MANYCORE_DIR) \
	-DCL_MANYCORE_DIM_X=$(CL_MANYCORE_DIM_X) \
	-DCL_MANYCORE_DIM_Y=$(CL_MANYCORE_DIM_Y) \
	-DBSG_PYTHON_TEST_PATH=$(abspath $(BSG_F1_DIR)/regression/python/)

CFLAGS   += -std=c11 $(shell python3.6-config --cflags)
LDFLAGS  += $(shell python3.6-config --ldflags)


