REGRESSION_TESTS_TYPE = python

UNIFIED_MAIN_TESTS = test_python

INDEPENDENT_MAIN_TESTS := 

REGRESSION_TESTS = $(UNIFIED_MAIN_TESTS) $(INDEPENDENT_MAIN_TESTS)
COSIM_REGRESSION_TESTS = $(REGRESSION_TESTS)

PYTHON_TEST_PATH = $(abspath $(BSG_F1_DIR)/cl_manycore/regression/python/)

DEFINES += -DBSG_MANYCORE_DIR=$(abspath $(BSG_MANYCORE_DIR))
DEFINES += -DCL_MANYCORE_DIM_X=$(CL_MANYCORE_DIM_X) 
DEFINES += -DCL_MANYCORE_DIM_Y=$(CL_MANYCORE_DIM_Y)
DEFINES += -DBSG_PYTHON_TEST_PATH=$(PYTHON_TEST_PATH)
DEFINES += -D_XOPEN_SOURCE=500 -D_BSD_SOURCE

CDEFINES   += $(DEFINES)
CXXDEFINES += $(DEFINES)

FLAGS     = -g -Wall -Werror $(shell python3.6-config --cflags)
CFLAGS   += -std=c99 $(FLAGS)
CXXFLAGS += -std=c++11 $(FLAGS)
LDFLAGS  += -lbsg_manycore_runtime -lm
LDFLAGS  += $(shell python3.6-config --ldflags) 

.PHONY: help test_%.clean

help:
	@echo "To make a specific test run: make <testname> and then execute the resulting binary"
