#ifndef BSG_MANYCORE_REGS
#define BSG_MANYCORE_REGS

#define MMIO_FIFO_HOST 0x0
#define MMIO_FIFO_DEVICE 0x1
#define MMIO_FIFO_VACANCY_REG 0xC
#define MMIO_FIFO_WRITE_REG 0x10
#define MMIO_FIFO_TRANSMIT_LENGTH_REG 0x14
#define MMIO_FIFO_OCCUPANCY_REG 0x1C
#define MMIO_FIFO_READ_REG 0x20
#define MMIO_FIFO_RECEIVE_LENGTH_REG 0x24
#define MMIO_FIFO_ISR_REG 0x0 
#define MMIO_FIFO_IER_REG 0x4

#define hb_mc_mmio_get_fifo_reg(n, reg) (n * 0x1000 + reg)

#define MMIO_ROM_BASE 0x2000
#define MMIO_RECV_VACANCY_REG 0
#define MMIO_HOST_CREDITS_REG 8
#define MMIO_MANYCORE_NUM_X_REG 12
#define MMIO_MANYCORE_NUM_Y_REG 16

#endif
