#cloud-config
repo_update: true
repo_upgrade: all

runcmd:
 - 'sudo su - centos -c "ssh-keyscan github.com >> ~/.ssh/known_hosts"'
 - 'sudo su - centos -c "git clone git@github.com:bespoke-silicon-group/$release_repo.git"'
 - 'sudo su - centos -c "cd /home/centos/$release_repo; git checkout $release_hash"'
 - 'sudo su - centos -c "make -C /home/centos/$release_repo -f Makefile.amibuild -j4 install &> ~/amibuild.log"'
